#!/usr/bin/env python3
"""
Excel to C# data class export tool.
Usage: python3 export_tables.py <excel_folder_path>

config.xlsx columns:
  1: Excel file name (.xlsx)
  2: Export class name (.cs)
  3: Target output path
  4: Export type (0=list, 1=dictionary, 2=cfg)
  5: Key field name (dictionary only)
"""

import sys
import os

try:
    import openpyxl
except ImportError:
    print("Error: openpyxl is required. Install with: pip install openpyxl")
    sys.exit(1)


TYPE_LIST = 0
TYPE_DICT = 1
TYPE_CFG = 2
TYPE_NAMES = {TYPE_LIST: "List", TYPE_DICT: "Dictionary", TYPE_CFG: "Cfg"}


def read_config(config_path):
    wb = openpyxl.load_workbook(config_path, read_only=True)
    ws = wb.active
    configs = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or row[0] is None:
            continue
        excel_file = str(row[0]).strip()
        if not excel_file.endswith(".xlsx"):
            excel_file += ".xlsx"
        cs_file = str(row[1]).strip()
        if not cs_file.endswith(".cs"):
            cs_file += ".cs"
        target_path = str(row[2]).strip()
        export_type = int(row[3])
        key = str(row[4]).strip() if len(row) > 4 and row[4] is not None else None
        configs.append(
            {
                "excel_file": excel_file,
                "cs_file": cs_file,
                "target_path": target_path,
                "export_type": export_type,
                "key": key,
            }
        )
    wb.close()
    return configs


def read_data_table(file_path):
    wb = openpyxl.load_workbook(file_path, read_only=True)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    wb.close()
    if len(rows) < 3:
        raise ValueError(f"Data table {file_path} must have at least 3 rows")

    types = [str(c).strip() if c else "" for c in rows[1]]
    fields = [str(c).strip() if c else "" for c in rows[2]]

    valid = [i for i in range(len(fields)) if fields[i]]
    types = [types[i] for i in valid]
    fields = [fields[i] for i in valid]

    data = []
    for row in rows[3:]:
        if all(c is None for c in row):
            continue
        data.append([row[i] if i < len(row) else None for i in valid])

    return types, fields, data


def format_value(value, ctype):
    if value is None:
        defaults = {
            "string": '""',
            "bool": "false",
            "float": "0f",
            "double": "0d",
            "long": "0L",
        }
        return defaults.get(ctype, "0")
    if ctype == "string":
        return f'"{value}"'
    if ctype == "bool":
        return "true" if str(value).lower() in ("true", "1", "yes") else "false"
    if ctype == "int":
        return str(int(float(value)))
    if ctype == "float":
        v = float(value)
        return f"{int(v)}f" if v == int(v) else f"{v}f"
    if ctype == "double":
        return f"{value}d"
    if ctype == "long":
        return f"{int(float(value))}L"
    return str(value)


def derive_entry_name(class_name):
    base = class_name[2:] if class_name.startswith("Gd") else class_name
    return base + "Entry"


def gen_list(cls, entry, types, fields, data):
    lines = [
        "// Auto-generated by export_tables.py, do not modify manually",
        "using System.Collections.Generic;",
        "",
        f"public class {entry}",
        "{",
    ]
    for t, f in zip(types, fields):
        lines.append(f"    public {t} {f} {{ get; init; }}")
    lines += ["}", "", f"public class {cls}", "{"]
    lines.append(f"    private static readonly {entry}[] _data = new {entry}[]")
    lines.append("    {")
    for row in data:
        props = ", ".join(
            f"{f} = {format_value(v, t)}" for f, t, v in zip(fields, types, row)
        )
        lines.append(f"        new {entry} {{ {props} }},")
    lines += ["    };", ""]
    lines.append(f"    public static IReadOnlyList<{entry}> Data => _data;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_dict(cls, entry, types, fields, data, key):
    ki = fields.index(key)
    kt = types[ki]
    lines = [
        "// Auto-generated by export_tables.py, do not modify manually",
        "using System.Collections.Generic;",
        "",
        f"public class {entry}",
        "{",
    ]
    for t, f in zip(types, fields):
        lines.append(f"    public {t} {f} {{ get; init; }}")
    lines += ["}", "", f"public class {cls}", "{"]
    lines.append(
        f"    private static readonly Dictionary<{kt}, {entry}> _data = new Dictionary<{kt}, {entry}>"
    )
    lines.append("    {")
    for i, row in enumerate(data):
        kv = format_value(row[ki], kt)
        props = ", ".join(
            f"{f} = {format_value(v, t)}" for f, t, v in zip(fields, types, row)
        )
        comma = "," if i < len(data) - 1 else ""
        lines.append(f"        {{{kv}, new {entry} {{ {props} }}}}{comma}")
    lines += ["    };", ""]
    lines.append(f"    public static Dictionary<{kt}, {entry}> Data => _data;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_cfg(cls, entry, types, fields, data):
    if len(data) != 1:
        raise ValueError(
            f"Cfg type for {cls} must have exactly 1 data row, got {len(data)}"
        )
    row = data[0]
    lines = [
        "// Auto-generated by export_tables.py, do not modify manually",
        "",
        f"public class {entry}",
        "{",
    ]
    for t, f in zip(types, fields):
        lines.append(f"    public {t} {f} {{ get; init; }}")
    lines += ["}", "", f"public class {cls}", "{"]
    lines.append(f"    private static readonly {entry} _data = new {entry}")
    lines.append("    {")
    for i, (f, t, v) in enumerate(zip(fields, types, row)):
        comma = "," if i < len(fields) - 1 else ""
        lines.append(f"        {f} = {format_value(v, t)}{comma}")
    lines += ["    };", ""]
    lines.append(f"    public static {entry} Data => _data;")
    lines.append("}")
    return "\n".join(lines) + "\n"


GENERATORS = {
    TYPE_LIST: lambda cls, entry, types, fields, data, _key: gen_list(
        cls, entry, types, fields, data
    ),
    TYPE_DICT: lambda cls, entry, types, fields, data, key: gen_dict(
        cls, entry, types, fields, data, key
    ),
    TYPE_CFG: lambda cls, entry, types, fields, data, _key: gen_cfg(
        cls, entry, types, fields, data
    ),
}


def main():
    if len(sys.argv) != 2:
        print(f"Usage: python3 {sys.argv[0]} <excel_folder_path>")
        sys.exit(1)

    folder = sys.argv[1]
    config_path = os.path.join(folder, "config.xlsx")
    if not os.path.exists(config_path):
        print(f"Error: config.xlsx not found in {folder}")
        sys.exit(1)

    configs = read_config(config_path)
    print(f"Found {len(configs)} table(s) to export")

    success_count = 0
    for cfg in configs:
        excel_path = os.path.join(folder, cfg["excel_file"])
        if not os.path.exists(excel_path):
            print(f"  [Skip] {cfg['excel_file']} not found")
            continue

        cls = cfg["cs_file"].replace(".cs", "")
        entry = derive_entry_name(cls)
        export_type = cfg["export_type"]

        if export_type == TYPE_DICT and not cfg["key"]:
            print(f"  [Error] Dictionary type requires a key for {cls}")
            continue

        if export_type not in GENERATORS:
            print(f"  [Error] Unknown export type {export_type} for {cls}")
            continue

        try:
            types, fields, data = read_data_table(excel_path)
            code = GENERATORS[export_type](cls, entry, types, fields, data, cfg["key"])
        except Exception as e:
            print(f"  [Error] {cls}: {e}")
            continue

        output_dir = cfg["target_path"]
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, cfg["cs_file"])

        with open(output_path, "w", encoding="utf-8-sig") as f:
            f.write(code)

        print(f"  [{TYPE_NAMES[export_type]}] {cfg['excel_file']} -> {output_path}")
        success_count += 1

    print(f"Export complete! ({success_count}/{len(configs)} succeeded)")


if __name__ == "__main__":
    main()
