// Auto-generated by export_tables.py, do not modify manually
using System.Collections.Generic;

public class SystemEntry
{
    public string SystemName { get; init; }
    public bool AutoInit { get; init; }
    public int Priority { get; init; }
}

public class GdSystem
{
    private static readonly SystemEntry[] _data = new SystemEntry[]
    {
        new SystemEntry { SystemName = "BattleSys", AutoInit = true, Priority = 0 },
    };

    public static IReadOnlyList<SystemEntry> Data => _data;
}
